INSERT INTO Categoria(DESCRIPCION) VALUES('Americana');
INSERT INTO Categoria(DESCRIPCION) VALUES('Italiana');
INSERT INTO Categoria(DESCRIPCION) VALUES('Mexicana');
INSERT INTO Categoria(DESCRIPCION) VALUES('Comida rapida');
INSERT INTO UNIDAD_MEDIDA(DESCRIPCION) VALUES('Cucharada pequeña');
INSERT INTO UNIDAD_MEDIDA(DESCRIPCION) VALUES('Cucharada');
INSERT INTO UNIDAD_MEDIDA(DESCRIPCION) VALUES('Taza');
INSERT INTO UNIDAD_MEDIDA(DESCRIPCION) VALUES('Pizca');
INSERT INTO UNIDAD_MEDIDA(DESCRIPCION) VALUES('Onza');